# docker-compose.yml
# services:
#   db:
#     image: postgres:16-alpine
#     environment:
#       POSTGRES_DB: smartcomments
#       POSTGRES_USER: dev
#       POSTGRES_PASSWORD: dev
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   backend:
#     build: ./backend
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - ./backend:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#     environment:
#       - DATABASE_URL=postgres://dev:dev@db:5432/smartcomments

# volumes:
#   postgres_data: